name: Import devices from issue
on:
  issues:
    types:
      - opened

premissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  import_devices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Extract CSV URL
        id: csv_url
        env:
          GITHUB_EVENT_ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          echo "Extracting CSV URL from issue body..."
          echo "csv_url=$(echo '$GITHUB_EVENT_ISSUE_BODY' | grep -oP 'http[s]?://[^)]+.csv')" >> $GITHUB_OUTPUT

      - name: Download CSV file and import devices
        id: import_devices
        env:
          CSV_URL: ${{ steps.csv_url.outputs.csv_url }}
        run: |
          echo "Downloading CSV file..."
          curl -L '$CSV_URL' -o to_process/data.csv
          echo "Importing devices from CSV file..."
          output=$(python script/process.py)
          output="${output//$'\n'/'%0A'}"
          echo "output=${output#*%0A%0A}" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        env:
          GITHUB_EVENT_ISSUE_NUMBER: ${{ github.event.issue.number }}
          PROCESS_OUTPUT: ${{ steps.import_devices.outputs.output }}
        with:
          commit-message: "Import devices from issue #$GITHUB_EVENT_ISSUE_NUMBER"
          title: "Import devices from issue #$GITHUB_EVENT_ISSUE_NUMBER"
          body: "This pull request imports devices from a CSV file linked in issue #$GITHUB_EVENT_ISSUE_NUMBER. Fixes #$GITHUB_EVENT_ISSUE_NUMBER\n\n$PROCESS_OUTPUT"
          branch: "import-devices-$GITHUB_EVENT_ISSUE_NUMBER"
          base: "main"

      - name: Comment on issue
        uses: actions/github-script@v7
        env:
          PROCESS_OUTPUT: ${{ steps.import_devices.outputs.output }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "$PROCESS_OUTPUT\n\nCreated pull request #${{ steps.create_pr.outputs.pull-request-number }}."
            });
